### ISSUE TITLE
where is the from attacks.fgsm import fgsm

### ISSUE THREAD

**Issue by EmotionalXX** [gongzhitaao/adversarial-classifier#1]
hello，sir：
the line:from attacks.fgsm import fgsm 
I can't find this file for attacks.fgsm,can you help me?

**Comment by gongzhitaao** [comment]
Hi, sorry for the confusion, the `attacks` folder contains code from https://github.com/gongzhitaao/tensorflow-adversarial/tree/master/attacks

I was too lazy to create s git submodule.

**Comment by EmotionalXX** [comment]
oh,thanks!
but there is still something wrong,do you know how to deal with it?
![image](https://user-images.githubusercontent.com/43211564/71735426-60580580-2e89-11ea-931a-b6232cd74314.png)

**Comment by gongzhitaao** [comment]
What tf version you have? If I remember correctly, I was using tf.1.3 or tf 1.4 which are really old.  I doubt the code is runnable as it is.  Unfortunately I'm not planning to upgrade the code to tf 1.15 or tf2.

But the general idea behind the code is rather simple, it would probably take ~1h to rewrite the code if you really want to reproduce it.

Hope this helps :smile:

**Comment by EmotionalXX** [comment]
> What tf version you have? If I remember correctly, I was using tf.1.3 or tf 1.4 which are really old. I doubt the code is runnable as it is. Unfortunately I'm not planning to upgrade the code to tf 1.15 or tf2.
> 
> But the general idea behind the code is rather simple, it would probably take ~1h to rewrite the code if you really want to reproduce it.
> 
> Hope this helps 😄

hello,Zhitao
I uesd tf 1.13 for this examination,but I can not run for it.and i have tried many times.
because this is important and first for me to make adversarial samples detection,I really want to make it.Maybe I need your help when you are free.

**Comment by gongzhitaao** [comment]
tf. 3 is definitely not compatible with tf 1.13.  So many things changed. You may need to rewrite part of the code or use https://github.com/tensorflow/cleverhans since it is still maintained AFAIK  Good luck :smile:
