### ISSUE TITLE
May I use it?

### ISSUE THREAD

**Issue by EmotionalXX** [gongzhitaao/adversarial-classifier#2]
Hello,sir.
May I need to train the binary classfier? Can not I use it to detect adversarial samples？

**Comment by gongzhitaao** [comment]
Sure. Feel feel to grab snippets of the code for your project. It is MIT-licence, so you are free to do anything :smile: 
The only thing I'm worried about is the version. The classifier was written with tf1.4, which is already deprecated. You might need to migrate some of the code to tf2.
Good luck!

**Comment by EmotionalXX** [comment]
Oh,that is good.Thank you!And is there code for training the binary classfier？

**Comment by gongzhitaao** [comment]
adversarial-classifier/src/table_1_mnist.py
But it is just standard binary classifier, you could use whatever framework you like, e.g., tf2, pytorch, jax, etc.
